import type { Metadata } from "next"; 
import { Inter } from "next/font/google";
import "../../app/globals.css";
import InputField from "../../components/common/Chat/InputField";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <div className="fixed inset-x-0 bottom-0">
          <div className="flex justify-center items-center m-4">
            <InputField />
          </div>
        </div>
      </body>
    </html>
  );
}
